# -*- coding: utf-8 -*-
"""01_MCQ_Generator_with_HuggingFace_Locally_on_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kw3SJpCcHrVNd1ejxM-1wIXu3hWVquYR
"""

# !pip install -q -U transformers accelerate bitsandbytes langchain langchain-community langchain-huggingface PyPDF2 langchain-classic

import os
import json
import pandas as pd
import traceback
import torch
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, pipeline
from langchain_huggingface import HuggingFacePipeline

# 1. Define the model
model_id = "mistralai/Mistral-7B-Instruct-v0.3"

# 2. Configure 4-bit quantization to fit the model in Colab's 16GB VRAM
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

# 3. Load Tokenizer & Model
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)

# 4. Create the Text Generation Pipeline
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=1024,
    do_sample=True,
    temperature=0.5,
    return_full_text=False
)

# 5. Wrap in LangChain
llm = HuggingFacePipeline(pipeline=pipe)

from langchain_core.prompts import PromptTemplate
from langchain_classic.chains import LLMChain
from langchain_classic.chains import SequentialChain
import PyPDF2

RESPONSE_JSON = {
    "1": {
        "mcq": "multiple choice question",
        "options": {
            "a": "choice here",
            "b": "choice here",
            "c": "choice here",
            "d": "choice here",
        },
        "correct": "correct answer",
    },
    "2": {
        "mcq": "multiple choice question",
        "options": {
            "a": "choice here",
            "b": "choice here",
            "c": "choice here",
            "d": "choice here",
        },
        "correct": "correct answer",
    },
    "3": {
        "mcq": "multiple choice question",
        "options": {
            "a": "choice here",
            "b": "choice here",
            "c": "choice here",
            "d": "choice here",
        },
        "correct": "correct answer",
    },
}

TEMPLATE = """
<s>[INST]
You are an expert MCQ maker.
Create a quiz of {number} multiple choice questions for {subject} students in {tone} tone.
Make sure the questions are not repeated and conform to the text.

Text:
{text}

Format your response strictly as this JSON object:
{response_json}

Output ONLY the JSON.
[/INST]
"""

quiz_generation_prompt = PromptTemplate(
    input_variables=["text", "number", "subject", "tone", "response_json"],
    template=TEMPLATE
    )

quiz_chain=LLMChain(llm=llm, prompt=quiz_generation_prompt, output_key="quiz", verbose=True)

# Cell 66
TEMPLATE2 = """
<s>[INST]
You are an expert English grammarian and writer.
Evaluate the complexity of the following quiz questions:
{quiz}

Provide a complexity analysis (max 50 words).
[/INST]
"""

quiz_evaluation_prompt=PromptTemplate(input_variables=["subject", "quiz"], template=TEMPLATE)

review_chain=LLMChain(llm=llm, prompt=quiz_evaluation_prompt, output_key="review", verbose=True)

generate_evaluate_chain=SequentialChain(chains=[quiz_chain, review_chain], input_variables=["text", "number", "subject", "tone", "response_json"],
                                        output_variables=["quiz", "review"], verbose=True,)

file_path=r"/content/01_data.txt"

with open(file_path, 'r', encoding='utf-8') as file:
    TEXT = file.read()

print(TEXT)

# Serialize the Python dictionary into a JSON-formatted string
json.dumps(RESPONSE_JSON)

NUMBER=5
SUBJECT="biology"
TONE="simple"

response = generate_evaluate_chain(
    {
        "text": TEXT,
        "number": NUMBER,
        "subject": SUBJECT,
        "tone": TONE,
        "response_json": json.dumps(RESPONSE_JSON)
    }
)

response

quiz=response.get("quiz")

# Cell 45: Robust JSON Parsing
import json

# Get the raw output
raw_quiz_output = response.get("quiz", "")

# Find the start and end of the valid JSON object
start_index = raw_quiz_output.find('{')
end_index = raw_quiz_output.rfind('}') + 1

if start_index != -1 and end_index != -1:
    # Extract only the JSON part
    cleaned_quiz_str = raw_quiz_output[start_index:end_index]

    try:
        # Parse the cleaned string
        quiz = json.loads(cleaned_quiz_str)
        print("✅ JSON parsed successfully!")
    except json.JSONDecodeError as e:
        print(f"❌ JSON Parsing Failed: {e}")
        print("Raw content:", raw_quiz_output)
else:
    print("❌ No JSON brackets found in the output.")
    print("Raw content:", raw_quiz_output)

quiz_table_data = []
for key, value in quiz.items():
    mcq = value["mcq"]
    options = " | ".join(
        [
            f"{option}: {option_value}"
            for option, option_value in value["options"].items()
            ]
        )
    correct = value["correct"]
    quiz_table_data.append({"MCQ": mcq, "Choices": options, "Correct": correct})

quiz_table_data

quiz=pd.DataFrame(quiz_table_data)

quiz.to_csv("01_machinelearning.csv",index=False)